# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4a3d0562ea74b406e2c6bbd657b224e16dcac8584889d9752f82bd4f45624bfd282fae1517602a46a5999cf62fb417c2b75f8cf7c0536ba33b0dce83e95a2c

test:
  secret_key_base: 587b6243780c3ce08a7c4d48b180a9cc564f1a26d834f73a6d49df1bf5a5d56c20c1dfefe193639a467d919cd606b614c7ea55b54dd60c46b11958e62a5b7373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
